// ─── Emotes — todos los iconos personalizados ─────────────────────────────────
const EMOTE_IMAGES = {
  'aguja-hilo':          require('./aguja-hilo.png'),
  'agujero-negro':       require('./agujero-negro.png'),
  'aillo':               require('./aillo.png'),
  'ambulancia':          require('./ambulancia.png'),
  'arbol':               require('./arbol.png'),
  'autobus':             require('./autobus.png'),
  'avion':               require('./avion.png'),
  'balanza':             require('./balanza.png'),
  'banco':               require('./banco.png'),
  'barco':               require('./barco.png'),
  'bateria-full-2':      require('./bateria-full-2.png'),
  'bateria-full':        require('./bateria-full.png'),
  'bateria-low':         require('./bateria-low.png'),
  'bebe':                require('./bebe.png'),
  'biberon':             require('./biberon.png'),
  'bicicleta':           require('./bicicleta.png'),
  'bolsa-compra':        require('./bolsa-compra.png'),
  'bolso':               require('./bolso.png'),
  'bombilla':            require('./bombilla.png'),
  'brujula':             require('./brujula.png'),
  'bubble-tea':          require('./bubble-tea.png'),
  'cafe-2':              require('./cafe-2.png'),
  'cafe':                require('./cafe.png'),
  'caja-carton':         require('./caja-carton.png'),
  'caja-herramientas':   require('./caja-herramientas.png'),
  'caja-regalo':         require('./caja-regalo.png'),
  'calendario':          require('./calendario.png'),
  'cama':                require('./cama.png'),
  'camara-fotos':        require('./camara-fotos.png'),
  'camiseta':            require('./camiseta.png'),
  'caracol':             require('./caracol.png'),
  'carne':               require('./carne.png'),
  'carpeta':             require('./carpeta.png'),
  'carpetas':            require('./carpetas.png'),
  'carretera':           require('./carretera.png'),
  'carrito-compra':      require('./carrito-compra.png'),
  'carta':               require('./carta.png'),
  'cartera':             require('./cartera.png'),
  'casa':                require('./casa.png'),
  'casco-moto':          require('./casco-moto.png'),
  'cerebro-2':           require('./cerebro-2.png'),
  'cerebro':             require('./cerebro.png'),
  'cerveza':             require('./cerveza.png'),
  'chaqueta':            require('./chaqueta.png'),
  'chincheta':           require('./chincheta.png'),
  'chocolate':           require('./chocolate.png'),
  'claqueta':            require('./claqueta.png'),
  'clip-2':              require('./clip-2.png'),
  'clip':                require('./clip.png'),
  'coche':               require('./coche.png'),
  'cohete':              require('./cohete.png'),
  'comida-mascotas':     require('./comida-mascotas.png'),
  'comida-para-llevar':  require('./comida-para-llevar.png'),
  'copa':                require('./copa.png'),
  'corazon-manos':       require('./corazon-manos.png'),
  'corazon':             require('./corazon.png'),
  'corona-2':            require('./corona-2.png'),
  'corona':              require('./corona.png'),
  'cosmetico':           require('./cosmetico.png'),
  'creaneo-esqueleto':   require('./creaneo-esqueleto.png'),
  'cubo-rubik':          require('./cubo-rubik.png'),
  'cupon':               require('./cupon.png'),
  'dado':                require('./dado.png'),
  'destornillador':      require('./destornillador.png'),
  'diamante':            require('./diamante.png'),
  'diana':               require('./diana.png'),
  'diente':              require('./diente.png'),
  'dinamita':            require('./dinamita.png'),
  'dinero':              require('./dinero.png'),
  'dragon':              require('./dragon.png'),
  'edificio':            require('./edificio.png'),
  'emote-derritiendose': require('./emote-derritiendose.png'),
  'emote-dinero':        require('./emote-dinero.png'),
  'emote-gafas-sol':     require('./emote-gafas-sol.png'),
  'emote-llorar-feliz':  require('./emote-llorar-feliz.png'),
  'emote-llorar':        require('./emote-llorar.png'),
  'emote-ojos':          require('./emote-ojos.png'),
  'emote-si-señor':      require('./emote-si-señor.png'),
  'enchufe':             require('./enchufe.png'),
  'engranage':           require('./engranage.png'),
  'escoba':              require('./escoba.png'),
  'escudo-mascota':      require('./escudo-mascota.png'),
  'escudo':              require('./escudo.png'),
  'escuela':             require('./escuela.png'),
  'espadas':             require('./espadas.png'),
  'estadisticas':        require('./estadisticas.png'),
  'estrella-2':          require('./estrella-2.png'),
  'estrella-fugaz':      require('./estrella-fugaz.png'),
  'estrella':            require('./estrella.png'),
  'extintor':            require('./extintor.png'),
  'familia':             require('./familia.png'),
  'fiesta':              require('./fiesta.png'),
  'flor-loto':           require('./flor-loto.png'),
  'fuego':               require('./fuego.png'),
  'gafas':               require('./gafas.png'),
  'gasolinera':          require('./gasolinera.png'),
  'gato':                require('./gato.png'),
  'globo-terraqueo-2':   require('./globo-terraqueo-2.png'),
  'globo-terraqueo':     require('./globo-terraqueo.png'),
  'gorra':               require('./gorra.png'),
  'gorro-graduacion':    require('./gorro-graduacion.png'),
  'gota':                require('./gota.png'),
  'guitarra':            require('./guitarra.png'),
  'hacker':              require('./hacker.png'),
  'hamburguesa':         require('./hamburguesa.png'),
  'hucha-cerdo':         require('./hucha-cerdo.png'),
  'identificacion':      require('./identificacion.png'),
  'iglesia':             require('./iglesia.png'),
  'impresora':           require('./impresora.png'),
  'informe-dinero':      require('./informe-dinero.png'),
  'inversion':           require('./inversion.png'),
  'jabon':               require('./jabon.png'),
  'jeringuilla':         require('./jeringuilla.png'),
  'lapiz':               require('./lapiz.png'),
  'lavadora':            require('./lavadora.png'),
  'libro-abierto-2':     require('./libro-abierto-2.png'),
  'libro-abierto':       require('./libro-abierto.png'),
  'libro':               require('./libro.png'),
  'libros-2':            require('./libros-2.png'),
  'luz-emergencia-2':    require('./luz-emergencia-2.png'),
  'luz-emergencia':      require('./luz-emergencia.png'),
  'maleta':              require('./maleta.png'),
  'maletin':             require('./maletin.png'),
  'mando-consola':       require('./mando-consola.png'),
  'manos-trato-hecho':   require('./manos-trato-hecho.png'),
  'manos':               require('./manos.png'),
  'manzana':             require('./manzana.png'),
  'mapa':                require('./mapa.png'),
  'maquina-apuestas':    require('./maquina-apuestas.png'),
  'martillo':            require('./martillo.png'),
  'mascaras':            require('./mascaras.png'),
  'medico-2':            require('./medico-2.png'),
  'microfono':           require('./microfono.png'),
  'microscopio':         require('./microscopio.png'),
  'moneda':              require('./moneda.png'),
  'monitor':             require('./monitor.png'),
  'movil':               require('./movil.png'),
  'nota-musical-2':      require('./nota-musical-2.png'),
  'nota-musical':        require('./nota-musical.png'),
  'nube-tormenta':       require('./nube-tormenta.png'),
  'organizador':         require('./organizador.png'),
  'osito-peluche':       require('./osito-peluche.png'),
  'ovni':                require('./ovni.png'),
  'pan':                 require('./pan.png'),
  'pantalon':            require('./pantalon.png'),
  'papel-higienico':     require('./papel-higienico.png'),
  'papel':               require('./papel.png'),
  'parking':             require('./parking.png'),
  'pastillas':           require('./pastillas.png'),
  'patinete':            require('./patinete.png'),
  'patita':              require('./patita.png'),
  'peluqueria':          require('./peluqueria.png'),
  'perro':               require('./perro.png'),
  'pesa':                require('./pesa.png'),
  'pez':                 require('./pez.png'),
  'pintura':             require('./pintura.png'),
  'pizza':               require('./pizza.png'),
  'planta':              require('./planta.png'),
  'playa':               require('./playa.png'),
  'pluma-escribir':      require('./pluma-escribir.png'),
  'portatil':            require('./portatil.png'),
  'puerta':              require('./puerta.png'),
  'queso':               require('./queso.png'),
  'rana':                require('./rana.png'),
  'rayo':                require('./rayo.png'),
  'reciclaje':           require('./reciclaje.png'),
  'reloj':               require('./reloj.png'),
  'repeticion':          require('./repeticion.png'),
  'robot':               require('./robot.png'),
  'salud':               require('./salud.png'),
  'señal':               require('./señal.png'),
  'sierra':              require('./sierra.png'),
  'signo-interrogacion': require('./signo-interrogacion.png'),
  'silla':               require('./silla.png'),
  'sofa':                require('./sofa.png'),
  'sudadera':            require('./sudadera.png'),
  'supermercado':        require('./supermercado.png'),
  'sushi':               require('./sushi.png'),
  'tarjeta':             require('./tarjeta.png'),
  'taxi':                require('./taxi.png'),
  'teclado':             require('./teclado.png'),
  'telescopio':          require('./telescopio.png'),
  'television':          require('./television.png'),
  'tenedor-cuchillo':    require('./tenedor-cuchillo.png'),
  'ticket':              require('./ticket.png'),
  'tienda':              require('./tienda.png'),
  'tienda-campaña':      require('./tienda-campaña.png'),
  'tornado':             require('./tornado.png'),
  'trampa':              require('./trampa.png'),
  'tren':                require('./tren.png'),
  'tren-bala':           require('./tren-bala.png'),
  'troefeo':             require('./troefeo.png'),
  'tumba':               require('./tumba.png'),
  'vampiro':             require('./vampiro.png'),
  'varita':              require('./varita.png'),
  'vasito-quimico':      require('./vasito-quimico.png'),
  'vestido':             require('./vestido.png'),
  'videojuegos':         require('./videojuegos.png'),
  'yoga':                require('./yoga.png'),
  'zapatilla':           require('./zapatilla.png'),
  'zapato':              require('./zapato.png'),
  'zorro':               require('./zorro.png'),
  'zumo':                require('./zumo.png'),
};

export const ALL_EMOTE_KEYS = Object.keys(EMOTE_IMAGES);

// ─── Emotes organizados por grupo ─────────────────────────────────────────────
export const EMOTE_GROUPS = [
  {
    label: 'Alimentación',
    keys: [
      'supermercado','carrito-compra','bolsa-compra','hamburguesa','pizza','sushi',
      'pan','queso','manzana','carne','tenedor-cuchillo','cafe','cafe-2','bubble-tea',
      'zumo','cerveza','copa','aillo','chocolate',
    ],
  },
  {
    label: 'Transporte',
    keys: [
      'coche','autobus','tren','tren-bala','avion','barco','bicicleta','patinete',
      'taxi','casco-moto','carretera','gasolinera','parking','brujula','mapa',
    ],
  },
  {
    label: 'Hogar',
    keys: [
      'casa','sofa','cama','lavadora','impresora','television','monitor','enchufe',
      'bombilla','caja-herramientas','martillo','destornillador','escoba','sierra',
      'papel-higienico','jabon','puerta','silla','planta','luz-emergencia','luz-emergencia-2',
    ],
  },
  {
    label: 'Salud & Bienestar',
    keys: [
      'medico-2','ambulancia','jeringuilla','pastillas','microscopio','salud','diente',
      'pesa','yoga','cerebro','cerebro-2','vasito-quimico','extintor','mascaras',
    ],
  },
  {
    label: 'Tecnología',
    keys: [
      'portatil','movil','teclado','monitor','impresora','camara-fotos','bateria-full',
      'bateria-full-2','bateria-low','robot','hacker','telescopio','videojuegos',
      'mando-consola','enchufe','nube-tormenta',
    ],
  },
  {
    label: 'Ocio & Entretenimiento',
    keys: [
      'videojuegos','mando-consola','guitarra','nota-musical','nota-musical-2',
      'microfono','claqueta','cubo-rubik','dado','diana','maquina-apuestas',
      'fiesta','mascaras','telescopio','pintura','camara-fotos','playa',
      'tienda-campaña','globo-terraqueo','globo-terraqueo-2',
    ],
  },
  {
    label: 'Ropa & Moda',
    keys: [
      'camiseta','chaqueta','sudadera','pantalon','vestido','zapato','zapatilla',
      'bolso','gorra','gafas','emote-gafas-sol','aguja-hilo','cosmetico',
    ],
  },
  {
    label: 'Finanzas & Trabajo',
    keys: [
      'dinero','moneda','tarjeta','hucha-cerdo','banco','inversion','informe-dinero',
      'estadisticas','balanza','maletin','maleta','cartera','cupon','ticket',
      'diamante','troefeo','corona','corona-2','emote-dinero','identificacion',
    ],
  },
  {
    label: 'Compras',
    keys: [
      'bolsa-compra','carrito-compra','tienda','caja-carton','caja-regalo','ticket',
      'cupon','organizador',
    ],
  },
  {
    label: 'Familia & Social',
    keys: [
      'familia','bebe','biberon','osito-peluche','corazon','corazon-manos','manos',
      'manos-trato-hecho','iglesia','escuela','gorro-graduacion','carta','chincheta',
    ],
  },
  {
    label: 'Mascotas & Naturaleza',
    keys: [
      'gato','perro','pez','rana','zorro','dragon','caracol','patita','escudo-mascota',
      'comida-mascotas','arbol','flor-loto','planta','gota','nube-tormenta',
      'fuego','rayo','tornado',
    ],
  },
  {
    label: 'Viajes',
    keys: [
      'avion','maleta','brujula','mapa','globo-terraqueo','globo-terraqueo-2',
      'playa','tienda-campaña','barco','tren-bala','taxi','cohete','ovni',
    ],
  },
  {
    label: 'Educación & Cultura',
    keys: [
      'libro','libro-abierto','libro-abierto-2','libros-2','lapiz','pluma-escribir',
      'papel','carpeta','carpetas','escuela','gorro-graduacion','clip','clip-2',
      'calendario','reloj',
    ],
  },
  {
    label: 'Símbolos & Misc',
    keys: [
      'estrella','estrella-2','estrella-fugaz','corazon','rayo','fuego','escudo',
      'espadas','signo-interrogacion','reciclaje','repeticion','señal','chincheta',
      'bombilla','engranage','varita','dinamita','trampa','agujero-negro',
      'creaneo-esqueleto','tumba','vampiro','emote-si-señor',
    ],
  },
  {
    label: 'Emociones',
    keys: [
      'emote-derritiendose','emote-dinero','emote-gafas-sol','emote-llorar',
      'emote-llorar-feliz','emote-ojos','emote-si-señor','corazon','corazon-manos',
    ],
  },
];

export default EMOTE_IMAGES;
